name: mosquito
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  ar_flutter_plugin: ^0.7.3
  vector_math: ^2.1.0
  audioplayers: ^6.1.0
  permission_handler: ^10.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/models/
